server:
  port: 9001
jwt:
  config: xyy
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/login?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    port: 6379
    host: localhost
    database: 0
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 2000
        max-wait: 1000
      testOnBorrow: true
logging:
  level:
    com.example.xyy.mapper: debug  #dao的路径

